# Generated by Django 5.1 on 2024-11-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
