# Generated by Django 5.1 on 2024-11-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteApp', '0005_usuario_django_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
