# Generated by Django 5.1 on 2024-11-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('fecha_publicacion', models.DateField()),
                ('genero', models.CharField(choices=[('ACCION', 'accion'), ('ACCION Y AVENTURA', 'accion y aventura'), ('CASUAL', 'casual'), ('ESTRATEGIA', 'estrategia'), ('SHOOTERS', 'shooters'), ('DEPORTES', 'deportes'), ('RPG', 'rpg'), ('SIMULACION', 'simulacion'), ('MMO', 'mmo'), ('MMORPG', 'mmorpg')], max_length=20)),
                ('empresa', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=255)),
                ('pg', models.CharField(choices=[('G', 'Todas las edades'), ('PG', 'Inadecuado para niños'), ('R', 'Diciesiete años en adelante'), ('X', 'Mayores de edad')], max_length=18)),
                ('horas_juego', models.IntegerField()),
                ('oferta', models.IntegerField(choices=[('0%', '0%'), ('5%', '5%'), ('10%', '10%'), ('15%', '15%'), ('20%', '20%'), ('25%', '25%'), ('30%', '30%'), ('35%', '35%'), ('40%', '40%'), ('45%', '45%'), ('50%', '50%'), ('55%', '55%'), ('60%', '60%'), ('65%', '65%'), ('70%', '70%'), ('75%', '75%'), ('80%', '80%'), ('85%', '85%'), ('90%', '90%')])),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
