# Generated by Django 5.1 on 2024-11-26 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosApp', '0004_alter_juego_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='nombre',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
